///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;
using AppLayer.AppiumService;
using AppLayer.Modules;
using OpenQA.Selenium;
using AppLayer;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace DesktopWeb
{
	public partial class TC1:CommonHelper
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }
        
        private void ClickCountry(string pId,string pExpectedCountry)
        {
        	WebSpecific.SelectComboBoxItem(By.Id(pId),pExpectedCountry);
        }
        
        private void ValidateSelectedValue(string pId,string pExpectedCountry)
        {
        	var lvComboBoxValue = WebSpecific.GetSelectedComboboxValue(By.Id(pId));  //Element Search
        	IWebElement elem = string.Empty;
        	
        	
        	
        	if(lvComboBoxValue.Equals(pExpectedCountry,StringComparison.InvariantCultureIgnoreCase))
        	{
        		Logger.logSnapshot(elem);
        	}
        	else
        		Report.Log(ReportLevel.Failure,"COMBO BOX VAUE IS not EXPECTED");
        }
    }
}
